Server:
  RunMode: debug
  HttpPort: 9999
  ReadTimeout: 60
App:
  DefaultPageSIze: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:9999/static
  UploadImageMaxSize: 5 #MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
Database:
  DBType: mysql
  Username: changliang
  Password: changliang
  Host: 211.159.180.243
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 100
  MaxOpenConns: 3000
  #ConnMaxLifetime: 300